<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	class SkillsRepository {
		private $_pdo;
		private $_lang;
		private $_pdoHelper;

		public function __construct($pdo, $lang){
			$this->_pdoHelper = $pdo;
			$this->_pdo = $pdo->GetConnection();
			$this->_lang = $lang;
		}

		/**************************
		 * REPOSITORIES FUNCTIONS *
		 **************************/
		public function getAll(){
			$query = "SELECT * FROM skills";
			try {
				return $this->_pdoHelper->SelectTable($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function getById($id){
			$query = "SELECT * FROM skills WHERE id=" . $id;
			try {
				$properties = $this->_pdoHelper->Select($query);
				$object = new Skills();
				$object->fillObject($properties);
				return $object;
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function delete($id) {
			$query = "DELETE FROM skills WHERE id=" . $id;
			try {
				return $this->_pdoHelper->Query($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function add($properties) {
			$query = "INSERT INTO skills('id', 'title', 'mark', 'category', 'dCrea')
				VALUES(" . $properties["id"] . ", '" . $properties["title"] . "', " . $properties["mark"] . ", '" . $properties["category"] . "', '" . $properties["dCrea"] . "')";
			try {
				return $this->_pdoHelper->Query($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}

		public function update($id, $properties) {
			$query = "UPDATE skills 
				SET id = " . $properties["id"] . ", title = '" . $properties["title"] . "', mark = " . $properties["mark"] . ", category = '" . $properties["category"] . "', dCrea = '" . $properties["dCrea"] . "'
				WHERE id=" . $id;
			try {
				return $this->_pdoHelper->Query($query);
			}
			catch(PDOException $e){
				print $e->getMessage();
			}
			return array();
		}
		/*******
		 * END *
		 *******/

	}
?>