<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Entity;

	use fitzlucassen\FLFramework\Library\Core as cores;

	class Company {
		private $_id;
		private $_title;
		private $_description;
		private $_period;
		private $_image;
		private $_url;
		private $_queryBuilder;

		public function __construct($id = "", $title = "", $description = "", $period = "", $image = "", $url = ""){
			$this->_queryBuilder = new cores\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "title" => $title, "description" => $description, "period" => $period, "image" => $image, "url" => $url));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getTitle() {
			return $this->_title;
		}
		public function getDescription() {
			return $this->_description;
		}
		public function getPeriod() {
			return $this->_period;
		}
		public function getImage() {
			return $this->_image;
		}
		public function getUrl() {
			return $this->_url;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["title"]))
				$this->_title = $properties["title"];
			if(!empty($properties["description"]))
				$this->_description = $properties["description"];
			if(!empty($properties["period"]))
				$this->_period = $properties["period"];
			if(!empty($properties["image"]))
				$this->_image = $properties["image"];
			if(!empty($properties["url"]))
				$this->_url = $properties["url"];
		}
	}
