<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Entity;

	use fitzlucassen\FLFramework\Library\Core as cores;

	class Degree {
		private $_id;
		private $_title;
		private $_description;
		private $_school;
		private $_period;
		private $_queryBuilder;

		public function __construct($id = "", $title = "", $description = "", $school = "", $period = ""){
			$this->_queryBuilder = new cores\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "title" => $title, "description" => $description, "school" => $school, "period" => $period));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getTitle() {
			return $this->_title;
		}
		public function getDescription() {
			return $this->_description;
		}
		public function getSchool() {
			return $this->_school;
		}
		public function getPeriod() {
			return $this->_period;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["title"]))
				$this->_title = $properties["title"];
			if(!empty($properties["description"]))
				$this->_description = $properties["description"];
			if(!empty($properties["school"]))
				$this->_school = $properties["school"];
			if(!empty($properties["period"]))
				$this->_period = $properties["period"];
		}
	}
