<?php 
    /**********************************************************
     **** File generated by fitzlucassen\DALGenerator tool ****
     * All right reserved to fitzlucassen repository on github*
     ************* https://github.com/fitzlucassen ************
     **********************************************************/
    class Lang {
	private $_id;
	private $_code;

	public function __construct($id, $code){
	    $this->fillObject(array("id" => $id, "code" => $code));
	}

	/***********
	 * GETTERS *
	 ***********/
	/**
	 * 
	 * @return type
	 */
	public function getId() {
	    return $this->_id;
	}
	/**
	 * 
	 * @return type
	 */
	public function getCode() {
	    return $this->_code;
	}
	/*******
	 * END *
	 *******/

	/**
	 * 
	 * @param type $properties
	 */
	public function fillObject($properties) {
	    $this->_id = $properties["id"];
	    $this->_code = $properties["code"];
	}
    }